#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
cd ./openfoam
restore0Dir
runApplication blockMesh
runApplication decomposePar

cd ../
mpiexec -n 2 CPLIcoFoam -case ./openfoam -parallel : -n 2 lmp_cpl -i lammps.in
#mpiexec -n 2 CPLinterCondensatingEvaporatingFoam -parallel : -n 2 python3 ./minimal_MD.py

#------------------------------------------------------------------------------
